.......FE
======================================================================
ERROR: test_list_int (__main__.Test09_report_historical)
*** Test09 **** FUNCTION CALL: weather.report_historical(data={"20210203075501": {"t": 55, "h": 87, "r": 0}, "20210203090602": {"t": 63, "h": 84, "r": 0}, "20210203102903": {"t": 71, "h": 79, "r": 0}, "20210203125504": {"t": 72, "h": 69, "r": 0}, "20210203183905": {"t": 59, "h": 75, "r": 0}, "20210205044406": {"t": 57, "h": 68, "r": 0.01}, "20210205083307": {"t": 65, "h": 63, "r": 0.05}, "20210205122208": {"t": 73, "h": 56, "r": 0.11}, "20210205161109": {"t": 74, "h": 60, "r": 0.19}}) *** EXPECT: <look in test.py Test09 variable = report> ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elithomas/Documents/CPSC223P/CPSC223P-Lab6/test.py", line 110, in test_list_int
    r = weather.report_historical(data={"20210203075501": {"t": 55, "h": 87, "r": 0}, "20210203090602": {"t": 63, "h": 84, "r": 0}, "20210203102903": {"t": 71, "h": 79, "r": 0}, "20210203125504": {"t": 72, "h": 69, "r": 0}, "20210203183905": {"t": 59, "h": 75, "r": 0}, "20210205044406": {"t": 57, "h": 68, "r": 0.01}, "20210205083307": {"t": 65, "h": 63, "r": 0.05}, "20210205122208": {"t": 73, "h": 56, "r": 0.11}, "20210205161109": {"t": 74, "h": 60, "r": 0.19}})
AttributeError: module 'weather' has no attribute 'report_historical'

======================================================================
FAIL: test_list_int (__main__.Test08_report_daily)
*** Test08 **** FUNCTION CALL: weather.report_daily(data={"20210203075501": {"t": 55, "h": 87, "r": 0}, "20210203090602": {"t": 63, "h": 84, "r": 0}, "20210203102903": {"t": 71, "h": 79, "r": 0}, "20210203125504": {"t": 72, "h": 69, "r": 0}, "20210203183905": {"t": 59, "h": 75, "r": 0}, "20210205044406": {"t": 57, "h": 68, "r": 0.01}, "20210205083307": {"t": 65, "h": 63, "r": 0.05}, "20210205122208": {"t": 73, "h": 56, "r": 0.11}, "20210205161109": {"t": 74, "h": 60, "r": 0.19}}, date='20210205') *** EXPECT: <look in test.py Test08 variable = report> ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elithomas/Documents/CPSC223P/CPSC223P-Lab6/test.py", line 101, in test_list_int
    self.assertEqual(report, r)
AssertionError: '====[195 chars]uary 5, 2021      04:44:06           57       [206 chars]19\n' != '====[195 chars]uary 05, 2021     04:44:06           57       [204 chars]0.19'
Diff is 905 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 9 tests in 0.003s

FAILED (failures=1, errors=1)
